# Install wget requirement
- name: Install wget package
  yum:
    name:
      - wget
      - kairosdb
    state: present
  when: not ansible_check_mode

- name: Applying KairosDB configuration template
  template:
    src: kairosdb.properties.j2
    dest: /opt/kairosdb/conf/kairosdb.properties
  notify:
    - restart kairosdb

- name: Wait for Cassandra
  wait_for:
    host: "{{ kairosdb_cassandra_rpc_address }}"
    port: "{{ kairosdb_cassandra_rpc_port }}"
  when: kairosdb_wait_for_cassandra is defined and kairosdb_wait_for_cassandra

- name: Start KairosDB service
  service:
    name: kairosdb
    state: started
    enabled: yes
