---
- name: Install RabbitMQ
  yum:
    name: rabbitmq-server
    state: present
  when: not ansible_check_mode

- name: Start and enable RabbitMQ service
  service: name=rabbitmq-server state=started enabled=yes
  when: not ansible_check_mode

- name: RabbitMQ config files
  template:
    src: ../templates/rabbitmq.config.j2
    dest: /etc/rabbitmq/rabbitmq.config
    owner: root
    group: rabbitmq
    mode: 0644
  notify: restart rabbitmq

- name: Enable the plugins is installed
  rabbitmq_plugin:
    names: "{{ item }}"
    state: enabled
    new_only: yes
  with_items: "{{ rabbitmq_plugins }}"
  notify: restart rabbitmq
  when: not ansible_check_mode

- rabbitmq_user:
    user: "{{ abiquo_rabbitmq_username }}"
    password: "{{ abiquo_rabbitmq_password }}"
    vhost: "{{ abiquo_rabbitmq_vhost }}"
    tags: administrator
    configure_priv: .*
    read_priv: .*
    write_priv: .*
    state: present
  when: not ansible_check_mode
